### ISSUE TITLE
Question. Sorry about it

### ISSUE THREAD

**Issue by Neftedollar** [Shmew/Feliz.Plotly#16]
How did you generate code fro Feliz? I didn't find any tool.
Can you help me?

**Comment by Shmew** [comment]
Hi @Neftedollar 

I have a [paket depdencency](https://github.com/Shmew/Feliz.Plotly/blob/master/paket.dependencies#L22) that pulls down the json schema that the plotly.js team uses to define their model. I then run the generator application to build out the bulk of the library.

**Comment by Neftedollar** [comment]
Thank you!

**Comment by Shmew** [comment]
No problem!
