### ISSUE TITLE
Show how to use rangebreaks in documentation.

### ISSUE THREAD

**Issue by sebfia** [Shmew/Feliz.Plotly#21]
I just came along this beautiful project and tried to compose a chart with a datetime x-axis where I would like to omit saturdays and sundays.
However after a few hours of trial and error I am still clueless.
Found an example of how this works in js here: https://codepen.io/MojtabaSamimi/pen/oNjvOBa?editors=0010

**Comment by Shmew** [comment]
Hey @sebfia,

Yep it wasn't your fault it wasn't working, looks like the schema that plotly.js uses didn't have the correct definitions so it wasn't being compiled correctly (as this library is generated from that file). I have fixed the issue and added a little syntactic sugar on top!

I also added an example for reference [here](https://shmew.github.io/Feliz.Plotly/#/Plotly/Examples/Financial/Candlestick/RangeBreaks)

This is released in version `1.4.1`. Feel free to re-open if you have any issues!

**Comment by sebfia** [comment]
That was fast! Thank you for the quick fix
