### ISSUE TITLE
Add support for DateTimeOffset

### ISSUE THREAD

**Issue by nojaf** [Shmew/Feliz.Plotly#26]
## Is your feature request related to a problem?

Hello, would it be possible to add support of DateTimeOffset as well?
![image](https://user-images.githubusercontent.com/2621499/121666972-1f1a4b00-caaa-11eb-963b-a00e5dcff80a.png)

## Describe the solution you'd like
Out of the box support would be nice.

## Describe alternatives you've considered
I probably can convert my DateTimeOffset to a DateTime, though I'm not really sure how to proceed there.

## Additional context
/

**Comment by Zaid-Ajaj** [comment]
> I probably can convert my DateTimeOffset to a DateTime, though I'm not really sure how to proceed there.

You can get the `DateTime` component using the `DateTime` property
```fs
let timestamp = DateTimeOffset.Now;
let date = timestamp.DateTime;
```
In Fable, both `DateTimeOffset` and `DateTime` are `Date` instances so you could even `unbox<DateTime>`. The only difference is that `DateTimeOffset` attaches a property to the `Date` instance to maintain the offset

**Comment by nojaf** [comment]
You lose the time information when calling ` timestamp.DateTime;`.
https://fable.io/repl/#?code=PTAEHUCcEsBcFNQGMD2ATRLKgDYoIZqj6gDO+AtgA46IBmkKFZ0GARvpALABQKV8AHagAygE9SCCr14ARfAgAq0CvADydOqXiwAdAAVO2gBQAiAEwAGAIwBOALSWAzPesBWUJYDsALjfmfABZrXSd3SwjTAEpdeQReAB8APlAqGEFYOmFTAFIAQVMgA&html=Q&css=Q

**Comment by Zaid-Ajaj** [comment]
The REPL snippet is calling `.Date`, not `.DateTime` which only returns the date component

**Comment by nojaf** [comment]
😮, ok my bad. Thanks for pointing this out Zaid!

**Comment by Zaid-Ajaj** [comment]
😉 No problem! I think you can leave the issue open, it would be a nice addition to have an overload that accepts `DateTimeOffset[]` and then convert to `DateTime` internally

**Comment by Shmew** [comment]
I just pushed version 2.1.0 that adds support for `DateTimeOffset` anywhere a `DateTime` was previously allowed. Let me know if you have any issues, and feel free to re-open this if so!

**Comment by nojaf** [comment]
Thanks, I've tested this and it works as expected.
