### ISSUE TITLE
Use consistent camelCase namings

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Shmew/Feliz.Plotly#4]
I see that a lot of properties have inconsistent naming convention, sometimes camelCased, some times two words merged into one and other times snake_cased properties. It is an idea to make them all camelCased from the F# API point of view?

For example
```fs
// FROM
layout.xaxis.showgrid false
layout.xaxis.showline true
layout.xaxis.tickfont [ ]
layout.paper_bgcolor (colors.rgb(254, 247, 234))
layout.plot_bgcolor (colors.rgb(254, 247, 234))
// TO
layout.xaxis.showGrid false
layout.xaxis.showLine true
layout.xaxis.tickFont [ ]
layout.paperBackgroundColor (colors.rgb(254, 247, 234))
layout.plotBackgroundColor (colors.rgb(254, 247, 234))
```

**Comment by Shmew** [comment]
The snake case is an oversight on my part. I'm not sure how to adjust the other methods because that's how they're defined in the json schema:

```
...
"showline": { ... },
...
```

I could try to find words within the method names but I'm not sure how easy to implement and consistent it would be.

**Comment by Shmew** [comment]
I've merged the new code that replaces the snake case with camel case.

**Comment by Zaid-Ajaj** [comment]
@Shmew if there are only a couple of those then I though that having a function to convert them can be doable:
```fs
let propertyMap = function
  | "showline" -> "showLine"
  | "showgrid" -> "showGrid"
  | "tickfont" -> "tickFont"
  | property -> property
```
but this is asking for trouble every time we miss one property and then change it, then it is a breaking change. If there are only a couple of such cases then it is OK but otherwise maybe not a good idea
