### ISSUE TITLE
Packaged nuget has no dependencies

### ISSUE THREAD

**Issue by Zaid-Ajaj** [Shmew/Feliz.Plotly#7]
Maybe something went wrong with the package but looking at the [published nuget](https://www.nuget.org/packages/Feliz.Plotly), it says it doesn't have any dependency but it does need Feliz/Fable.Core etc. Maybe because that is hard-coded in [paket.template](https://github.com/Shmew/Feliz.Plotly/blob/master/src/Feliz.Plotly/paket.template)? Can you try removing that file and instead provide package information from the `.fsproj` file?

**Comment by Shmew** [comment]
I fixed the template file, it now shows the correct dependencies

**Comment by Zaid-Ajaj** [comment]
Awesome!
