### ISSUE TITLE
Need to un-nest many properties

### ISSUE THREAD

**Issue by Shmew** [Shmew/Feliz.Plotly#8]
Resolution of namespaces when deeply nested requires module aliasing, and in cases like [this](https://shmew.github.io/Feliz.Plotly/#/Plotly/Examples/Bar/ColoredAndStyled) can't be resolved properly. 

Need to figure out the best way to preserve fluent api while removing nesting as much as possible. May be able to do something similar to [this](https://github.com/Shmew/Feliz.Plotly/blob/master/src/Feliz.Generator.Plotly/ApiParser.fs#L239) on a larger scale.

**Comment by Shmew** [comment]
Redesigned the code generation to fix all of the namespace collisions. It's going to be *less* safe than before, but at least it works. 🙃

**Comment by Zaid-Ajaj** [comment]
Nice!
